import styles from "./components/header.module.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={styles.body}>
          {children}
      </body>
    </html>
  );
}
